In [4]:
# creare lista di 50 elementi
import numpy as np
np.zeros (50, dtype= int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [7]:
# creare matrice 2*5 numeri interi 
np.ones ((2, 5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
# creare matrice 3x3 con valori 12.34
np.full((3, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [15]:
# creare lista di 10 elementi, che inizia da 6 e incrementa di 4
np.arange(6, 46 ,4)

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42])

In [17]:
# creare lista di elementi tra 0 e 100 distanziati di 5
np.linespace(0, 1, 5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [21]:
# creare matrice 1x10 di valori casuali tra 0 e 1
np.random.seed
np.random.random(3, 3)

TypeError: random() takes at most 1 positional argument (2 given)